[package]
name = "phantom-storage"
version.workspace = true
edition.workspace = true

[dependencies]
phantom-core = { workspace = true }
serde_json = { workspace = true }
fjall = "2"

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true }
rand = "0.8"
